### ISSUE TITLE
DEA Model

### ISSUE THREAD

**Issue by ankoanju** [ankoanju/COMP23G2#5]

**Comment by dplotkin118** [comment]
![right facing dea](https://user-images.githubusercontent.com/72698503/95681191-834bde80-0bac-11eb-8f38-c342fe69c6c7.png)
![left facing dea](https://user-images.githubusercontent.com/72698503/95681197-88109280-0bac-11eb-8e98-f5c82b869aa2.png)

**Comment by dplotkin118** [comment]
![left facing dea](https://user-images.githubusercontent.com/72698503/95681845-07539580-0bb0-11eb-9c4a-e9c32fbda4de.png)

**Comment by dplotkin118** [comment]
![right facing dea](https://user-images.githubusercontent.com/72698503/95682224-281cea80-0bb2-11eb-8f87-6d528987ee6a.png)
![left facing dea](https://user-images.githubusercontent.com/72698503/95682227-2a7f4480-0bb2-11eb-95e4-94eb92fa25ef.png)

no background
